### ISSUE TITLE
Enable Toggle Modal

### ISSUE THREAD

**Issue by happyshows** [ijlyttle/bsplus#38]
Hi,

There are cases where modal window should be triggered via observe event other than button clicks. Currently bsplus lacks capability to support such.
Please add.

example: when user clicked 3 times, popup modal to submit an issue.

**Comment by ijlyttle** [comment]
Hi,

Thanks for making this feature suggestion. 

I can see where such a thing would be useful, but I think that the goal of bsplus is to provide you a means to write the HTML that taps into Bootstraps Javascript API using the HTML itself. 

Would there be anything preventing you from extending the behavior of a modal window created using `bs_modal()` by writing such a javascript observer? 

http://getbootstrap.com/javascript/#via-javascript

You are likely aware of the **shinyjs** package which makes it easier to add Javascript extensions.

Does this help?
