### ISSUE TITLE
Question: How to embed help links in a datatable

### ISSUE THREAD

**Issue by iainmwallace** [ijlyttle/bsplus#41]
Hi,

Great package! 

I was wondering if you have any examples on how to annotate the columns in a datatable (https://rstudio.github.io/DT/) with help text similar to your input help documentation.

It would be really useful to be able to put a more detailed column definition with a modal or tool tip.

Thanks,

Iain

**Comment by ijlyttle** [comment]
Hi Iain (great name),

Thanks for the kind words!

I have not had time to look at this in detail, but I did have a quick look at the DT documentation for the [`datatable()` function](https://www.rdocumentation.org/packages/DT/versions/0.2/topics/datatable). There is a `colnames` argument to customize the header - if you can supply HTML to that argument, then you should be able to embed an icon that links to a modal, tooltip or popover.

Hope this helps!

**Comment by ijlyttle** [comment]
This starts to get at a solution: https://gist.github.com/ijlyttle/a9a5796b93c6f141d7a6b1e516b4971d

It is nowhere near finished, but maybe can help us shake loose some ideas.

**Comment by iainmwallace** [comment]
Thanks, that makes clear the approach.

Is there a step I need to do to enable the bootstrap theme? The output
doesn't look correct. I have a clean install with this wonderful AMI  (
http://www.louisaslett.com/RStudio_AMI/) + the libraries indicated in the
gist.

**Comment by iainmwallace** [comment]
Works when I bundle it up as a shiny app...
https://iainmwallace.shinyapps.io/tooltips/

Thanks! Hope you have a great memorial day :)
