### ISSUE TITLE
Adding code chunks to accordion

### ISSUE THREAD

**Issue by royfrancis** [ijlyttle/bsplus#51]
```
bs_accordion(id="id1") %>%
  bs_append(title="Check this", content="This is so cool.")
```

Instead of just the text, can I add code chunks with formatting into the content? Also, how do I set the state (collapsed/non-collapsed)?

**Comment by ijlyttle** [comment]
I think you would need to render the code-chunks into HTML, then capture that as the `content` that you would send to `bs_append()`. 

With an accordion, at most one panel can be open at a time - addressing this in #35
