### ISSUE TITLE
Shiny input label embed and radio group buttons

### ISSUE THREAD

**Issue by kaushik12** [ijlyttle/bsplus#59]
I am not able embed an icon and attach a modal to radioGroupButtons input type tag developed by shinywidgets @pvictor. Is this something that can be easily fixed?

`ERROR: class is: form-group shiny-input-container shiny-input-radiogroup shiny-input-container-inline, needs to be: form-group shiny-input-container`

**Comment by ijlyttle** [comment]
Can you provide a minimal reproducible example? It would help me to figure out possible-next-steps. You might find the [reprex](https://github.com/tidyverse/reprex) package to be useful.

**Comment by kaushik12** [comment]
Sure, here goes. 

``` r
library(shiny)
require(bsplus)
require(shinyWidgets)

modal_features <- 
  bs_modal(
    id = "modal_features",
    title="Features",
    body= "test",
    size="medium"
  )

ui <- fluidPage(
   sidebarLayout(
      sidebarPanel(
         radioGroupButtons(inputId = "plot_type",label="Plot type",
                           choices = c("A","B"),
                           justified = TRUE,status="primary") %>%
           shinyInput_label_embed(
             shiny_iconlink() %>%
               bs_attach_modal(id_modal = "modal_features")
           )
      ),
      mainPanel = verbatimTextOutput("text")
   )
)

server <- function(input, output) {
   output$text <- renderText({
     as.character(input$plot_type)
   })
}

# Run the application 
shinyApp(ui = ui, server = server)

#> 
#> Error in .tag_validate(tag, name = "div", class = "form-group shiny-input-container") : 
#> class is: form-group shiny-input-container shiny-input-radiogroup shiny-input-container-inline, 
#> needs to be: form-group shiny-input-container
```

<sup>Created on 2019-02-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by ijlyttle** [comment]
Hi @kaushik12 - Thanks for the reprex! This helped me see that an internal function, `.tag-validate()`, needed to be more-permissive about the classes, then helped me test that it was fixed.

**Comment by kaushik12** [comment]
Thanks a lot Ian for a quick turnaround! Appreciate the help!

**Comment by kbneitz** [comment]
What was the solution to your issue for this? I am having the same problem and have identical code that produces the same error

**Comment by kaushik12** [comment]
Just install the package from GitHub and you should be fine.

On Thu, Apr 25, 2019 at 9:01 PM kbneitz <notifications@github.com> wrote:

> What was the solution to your issue for this? I am having the same problem
> and have identical code that produces the same error
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ijlyttle_bsplus_issues_59-23issuecomment-2D486888450&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=Qat22piHrmRK5W-hREuQrF6s6TQFpZIXGjtDfLeAS5I&m=uJtuoiqjAR6aXViUCqyc7ngQVoUZjt6qfoWFTFeFPxY&s=oPPkTGRwtQhEw5i9SV8hyyN2zVdrvH6OpVw3pTYCLb4&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AC5ZOMS3AO52CZFQ7UAQ26TPSJH5XANCNFSM4GYO52DQ&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=Qat22piHrmRK5W-hREuQrF6s6TQFpZIXGjtDfLeAS5I&m=uJtuoiqjAR6aXViUCqyc7ngQVoUZjt6qfoWFTFeFPxY&s=jF1qjbr1AT6HVAgZIq5splYQFsbOTYavVo7nV3uVPvY&e=>
> .
>


-- 
Kaushik Mohan
Masters' Student
Dept. of Applied Statistics, Social Science, and Humanities
Steinhardt School of Culture, Education, and Human Development
New York University

Email: kaushik.s.mohan@nyu.edu, km4326@nyu.edu
Phone: +1 (408) 614 6008 <(408)%20614-6008>

**Comment by benoitballester** [comment]
Hi I ran into the same bug using the CRAN version of bsplus. Now using the github version, which works fine. 
Question: any chance of having the CRAN version patched too ? Cheers

**Comment by ijlyttle** [comment]
Yes - it's overdue for a release! Let me see what I can do...
