### ISSUE TITLE
Trouble loading markdown file for modal body

### ISSUE THREAD

**Issue by simondorfman** [ijlyttle/bsplus#69]
Hello,
I'm following the modal example [from here](https://ijlyttle.github.io/bsplus/reference/bs_modal.html):

`bs_modal(
  id = "modal_large",
  title = "I'm a modal",
  size = "large",
  body = includeMarkdown(system.file("markdown", "modal.md", package = "bsplus"))
)`

I changed `modal.md` to `documentation_modal.md`. I have the documentation_modal.md file in the same folder as my .Rmd file. But when I knit the html file and click the button, the model shows a blank body. It doesn't show any of my text in my documentation_modal.md. Have I found a bug? Or am I doing something wrong? Any tips? Thanks!

**Comment by ijlyttle** [comment]
When you use

```r
system.file("markdown", "modal.md", package = "bsplus")
```

you are telling R to get `"modal.md"` from a directory included with the package.

I'd suggest you try

```r
includeMarkdown("documentation_modal.md") 
```

**Comment by simondorfman** [comment]
Well that makes a lot of sense. Thanks so much for your help!
